### ISSUE TITLE
Images not fully loading

### ISSUE THREAD

**Issue by Lucane** [RafhaanShah/Earth-View-For-Muzei#2]
Occasionally I have an issue where some images are only partially loaded (part of the image is missing). Sometimes the whole image is missing (I get a black background).

I attached some examples.
Any idea what might be causing this?

Device: Xiaomi
Android 13 (MIUI Global v14.0.2)

Otherwise your add-on app works really well and I love the image selection! Wouldn't be surprised if this was a MIUI issue.

![Screenshot_2023-04-15-13-03-17-926_net nurik roman muzei](https://user-images.githubusercontent.com/7999446/232208289-85bb742e-f0b6-4e3c-80af-aa667b68ea0f.jpg)
![Screenshot_2023-04-15-13-03-00-330_net nurik roman muzei](https://user-images.githubusercontent.com/7999446/232208292-82be8f9c-9e2c-4345-bce1-e1dc476a7640.jpg)
![Screenshot_2023-04-15-13-02-49-867_net nurik roman muzei](https://user-images.githubusercontent.com/7999446/232208293-e3bd7436-7515-4821-aea9-874e88ecf475.jpg)

**Comment by RafhaanShah** [comment]
Hey thanks for raising this! Not sure why this would happen, but it's probably something to do with Muzei. This add-on app actually only just provides the image link and details to Muzei, which does the actual fetching and loading of images!

Unless the Earth View service changed their URLs, but then nothing should load 🤔 

I'd try clearing the cache on both this app and Muzei and seeing how it goes, sorry I can't be more help!
