### ISSUE TITLE
does not retrieve images

### ISSUE THREAD

**Issue by Torrecilla** [RafhaanShah/Earth-View-For-Muzei#3]
The app doesn't show it retrieve any image, although it does show name of the place it should display

**Comment by RafhaanShah** [comment]
The Google Earth image URLs must have changed, I will have a look

**Comment by Anderhar** [comment]
Users of the official Chrome extension (hasn't updated in 3 years) are complaining about the same, and homepage of the project no longer loads too. There is an [article](https://9to5google.com/2024/01/29/google-shuts-down-earth-view-wallpaper-collection/) on 9to5google.com.

**Comment by RafhaanShah** [comment]
Looks like they removed the image URLs and include the image as a base64 encoded string in the JSON response. Should be fixed in the next release
